// Automatically generated by astro-icon
// 4bd9284fbece6f4ef7c520c8641653b785488c1c0f992da4752a7d3aa277a83b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "close"
		| "github"
		| "hamburgerMenu"
		| "ideal"
		| "notion";
}