name = "ideal"
compatibility_date = "2025-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[observability]
enabled = true

[env.production]
pages_build_output_dir = "./dist"