name = "ideal"
compatibility_date = "2025-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# KV Binding for sessions (required by Cloudflare adapter)
[[kv_namespaces]]
binding = "SESSION"
id = "ideal-kv"