name = "ideal"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-04-19"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
