import { getCollection } from "astro:content";
import { generateFieldsForSemesters } from "./data/dataHandler.ts";
const dataCivil = await getCollection("civil");
const dataInfor = await getCollection("infor");
const dataIndu = await getCollection("indu");
const dataElectro = await getCollection("electro");
const dataCPA = await getCollection("cpa");
export const cpaDataHandler = generateFieldsForSemesters(dataCPA);
export const electroDataHanlder = generateFieldsForSemesters(dataElectro);
export const induDataHanlder = generateFieldsForSemesters(dataIndu);
export const inforDataHanlder = generateFieldsForSemesters(dataInfor);
export const civilDataHanlder =  generateFieldsForSemesters(dataCivil);
